export const environment = {
    production: true,
    platformProviderApiBaseUrl: 'https://mock-api-vitalwatch.azurewebsites.net/api/v1',
    plansEndpointPath: '/plans',
    organizationsEndpointPath: '/organizations',
    usersEndpointPath: '/users',
    subscriptionsEndpointPath: '/subscriptions',
    invitationsEndpointPath: '/invitations',
    checkoutSessionsEndpointPath: '/checkoutSessions',
    workAreasEndpointPath: '/workAreas',
    specialtiesEndpointPath: '/specialties',
    careTeamsEndpointPath: '/careTeams',
    teamMembersEndpointPath: '/teamMembers',
    riskAssessmentsEndpointPath: '/riskAssessments',
    clinicalAlertsEndpointPath: '/clinicalAlerts',
    preventiveActionsEndpointPath: '/preventiveActions',
    vitalSignAnomaliesEndpointPath: '/vitalSignAnomalies',
    vitalSignReadingsEndpointPath: '/vitalSignReadings',
    shiftRecordsEndpointPath: '/shiftRecords',
    auditLogsEndpointPath: '/auditLogs'
};